package com.qacorn.rongcloud.mapper;

import com.qacorn.rongcloud.domain.RongUser;
import com.qacorn.rongcloud.domain.RongUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RongUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rong_user
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    long countByExample(RongUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rong_user
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    int deleteByExample(RongUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rong_user
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    int deleteByPrimaryKey(Integer userIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rong_user
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    int insert(RongUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rong_user
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    int insertSelective(RongUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rong_user
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    List<RongUser> selectByExample(RongUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rong_user
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    RongUser selectByPrimaryKey(Integer userIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rong_user
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") RongUser record, @Param("example") RongUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rong_user
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    int updateByExample(@Param("record") RongUser record, @Param("example") RongUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rong_user
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    int updateByPrimaryKeySelective(RongUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rong_user
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    int updateByPrimaryKey(RongUser record);
}