package com.qacorn.rongcloud.domain;

import java.util.Date;

public class RongUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rong_user.user_index
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    private Integer userIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rong_user.user_id
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rong_user.user_phone
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rong_user.user_password
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rong_user.user_name
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rong_user.user_avatar
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    private String userAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rong_user.user_status
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    private Byte userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rong_user.create_time
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rong_user.last_update
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rong_user.user_index
     *
     * @return the value of rong_user.user_index
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public Integer getUserIndex() {
        return userIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rong_user.user_index
     *
     * @param userIndex the value for rong_user.user_index
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public void setUserIndex(Integer userIndex) {
        this.userIndex = userIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rong_user.user_id
     *
     * @return the value of rong_user.user_id
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rong_user.user_id
     *
     * @param userId the value for rong_user.user_id
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rong_user.user_phone
     *
     * @return the value of rong_user.user_phone
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rong_user.user_phone
     *
     * @param userPhone the value for rong_user.user_phone
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rong_user.user_password
     *
     * @return the value of rong_user.user_password
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rong_user.user_password
     *
     * @param userPassword the value for rong_user.user_password
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rong_user.user_name
     *
     * @return the value of rong_user.user_name
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rong_user.user_name
     *
     * @param userName the value for rong_user.user_name
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rong_user.user_avatar
     *
     * @return the value of rong_user.user_avatar
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public String getUserAvatar() {
        return userAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rong_user.user_avatar
     *
     * @param userAvatar the value for rong_user.user_avatar
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar == null ? null : userAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rong_user.user_status
     *
     * @return the value of rong_user.user_status
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rong_user.user_status
     *
     * @param userStatus the value for rong_user.user_status
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rong_user.create_time
     *
     * @return the value of rong_user.create_time
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rong_user.create_time
     *
     * @param createTime the value for rong_user.create_time
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rong_user.last_update
     *
     * @return the value of rong_user.last_update
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rong_user.last_update
     *
     * @param lastUpdate the value for rong_user.last_update
     *
     * @mbg.generated Tue May 07 11:54:57 CST 2019
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}